### ISSUE TITLE
Unable to hit breakpoints in ionic2 webpack bundled apps

### ISSUE THREAD

**Issue by neilyoung** [Microsoft/vscode-chrome-debug#130]
I'm unable to make this run
- Visual Studio Code
- ionic2 sample app
- sourcemaps enabled in tsconfig.json and webpack.config.js, sourcemaps are generated
- launch.json see below
```
{
	"version": "0.2.0",
	"configurations": [

		{
			"name": "Launch localhost with sourcemaps",
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost:8100",
			"sourceMaps": true,
            "diagnosticLogging": true,
			"webRoot": "${workspaceRoot}/www"
		}
	]
}

```
App launches fine, breakpoints in ts code not hit.

diagnostic logging brings this:

`›SourceMaps.setBP: /Users/me/Documents/Ionic/hello/app/pages/page2/page2.ts can't be resolved to a loaded script.`

**Comment by roblourens** [comment]
Suggestions - 
* Check your sourcemap file - do the 'sourceroot' and 'sources' properties make sense? 
* I updated the extension a couple days ago with a couple sourcemap bugfixes, try updating
* Share the part of your log around the 'scriptParsed' event for the js script - did it find and resolve the sourcemaps correctly?

**Comment by auchenberg** [comment]
Hi @neilyoung 

We just released a new version of this debugger. Can I get you to test again and let me know how things are working?

/k

**Comment by neilyoung** [comment]
@roblourens:
sources contains entries like that: "webpack:///./app/pages/tabs/tabs.ts"
sourceroute is ""
@auchenberg 
Still not working for me. The app is running (ionic serve) at localhost:8100. The attach launch config ends up in ECONNREFUSED 127.0.0.1:9222. Only this launch config starts the browser at least, but doesn't stop on breakpoints in ts code

**Comment by roblourens** [comment]
Looks alright as far as I can tell. Can you post more of the log, specifically the lines around the scriptParsed notification? Webpack can be tricky.

**Comment by neilyoung** [comment]
I'm currently not having it on top of my head how I did enable the diagnostic logging...Let me try to replicate that later

**Comment by roblourens** [comment]
You just need `"diagnosticLogging": true` in your launch config

**Comment by neilyoung** [comment]
Yes, thanks. Found the switch and the debug window is full of traces. But I'm unable to copy it out... I can only get the visible part...VSCode on a Mac

**Comment by neilyoung** [comment]
Maybe this helps: Whenever I try to place a breakpoint in a ts file I get this:

 ›SourceMaps.setBP: /Users/me/Documents/Ionic/hello/app/pages/page2/page2.ts can't be resolved to a loaded script.

The ts file is _definitely_ there

**Comment by roblourens** [comment]
Yeah, the console's view is virtualized, so you can't copy more than the visible portion. I think they have an issue to do something about that. I'm interested in the scriptParsed notification for the script that page2.ts builds to. It should have some info about the sourcemap and how it resolves the sources for that js script.

**Comment by neilyoung** [comment]
Something like this?

›From client: setBreakpoints({"source":{"path":"/Users/me/Documents/Ionic/hello/app/pages/page2/page2.ts"},"lines":[10],"breakpoints":[{"line":10}]})
  ›SourceMaps.setBP: /Users/me/Documents/Ionic/hello/app/pages/page2/page2.ts can't be resolved to a loaded script.
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"67","url":"http://localhost:8100/build/js/app.bundle.js","startLine":0,"startColumn":0,"endLine":63749,"endColumn":38,"executionContextId":2,"sourceMapURL":"app.bundle.js.map"}}

Sorry for late answer. Didn't get eMail notification regarding new posts here.

**Comment by faustomura** [comment]
yes!

›From client: setBreakpoints({"source":{"path":"c:\\dati\\ord-fausto\\progetti\\temp_apache_vhost_9085\\_template\\dev\\www\\app\\app.component.ts"},"lines":[24],"breakpoints":[{"line":24}]})
  ›SourceMaps.setBP: c:\dati\ord-fausto\progetti\temp_apache_vhost_9085\_template\dev\www\app\app.component.ts can't be resolved to a loaded script.

**Comment by neilyoung** [comment]
I have copied the entire log peace for peace and pasted it together. Maybe it helps

[log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/202584/log.txt)

**Comment by roblourens** [comment]
Thanks! This is the part I was looking for: 
`›SourceMap: creating SM for /Users/me/Documents/Ionic/hello/www/build/js/app.bundle.js
  ›SourceMap: no sourceRoot specified, using script dirname: /Users/me/Documents/Ionic/hello/www/build/js
  ›SourceMaps.scriptParsed: /Users/me/Documents/Ionic/hello/www/build/js/app.bundle.js was just loaded and has mapped sources: [...`

and in that list of sources you can see that the extension is resolving tabs.ts as `/Users/me/Documents/Ionic/hello/www/build/js/app/pages/tabs/tabs.ts` when the actual path is `/Users/me/Documents/Ionic/hello/app/pages/tabs/tabs.ts`. If you look at your app.bundle.js.map file, according to this, sourceRoot is empty or missing, and it will have an item under `sources` that's probably like `app/pages/tabs/tabs.ts`. So that's the problem, there's no way for the extension to actually resolve that TS file. You might be able to set your sourceRoot to something like `file:///Users/me/Documents/Ionic/hello/` so the path works out correctly. I can't tell you exactly what to do, but if you look at those lines in the debug log, you should be able to get it to work out correctly.

If this works in Chrome, that's probably because sources are inlined.

**Comment by neilyoung** [comment]
Well, I have experimented a lot with sourceRoot, to no avail. The current value is, btw not undefined, but

   "sourceRoot": "app/**/*"

which seems to not work. We are talking about the sourceRoot entry in tsConfig.json?

**Comment by neilyoung** [comment]
It is completely weird. With the latest beta, which now again drops webpack support (!?) I'm able to get a "sourceRoot" entry, but again - it doesn't help. I don't know where "wwwroot" comes from, there is no such a directory. sourceRoot = source seems to mean, that the sources are embedded, but all in all it is a big mess, nobody understands :(

›SourceMap: resolved sourceRoot /source/ -> /Users/me/Documents/Ionic/hello/wwwroot/source/

**Comment by roblourens** [comment]
I'm talking about the sourceRoot in your .js.map file, which may or may not originate from your tsconfig.json, depending on your build config. I don't think "app/*" is a valid sourceRoot - it's used as just a prefix to the entries in 'sources' in the sourcemap file. If it ends up as a relative path, it's resolved relative to the .js file. If it starts with '/', it's resolved relative to your webserver root (or here, the webRoot property).

What do you mean by beta? Of vscode?

**Comment by neilyoung** [comment]
Yes, then we are talking about the same sourceRoot. "Beta" means the latest Ionic2 beta. As you can see I have a source root now, but it is still not working

**Comment by roblourens** [comment]
Sorry, I'm not sure what to tell you now, unless you can share the project or something.

**Comment by neilyoung** [comment]
Thanks for the offer. Will prepare something

**Comment by neilyoung** [comment]
Unfortunately such an Ionic sample project is pretty big. I have uploaded it to another server.

http://maps.alphadex.de/hello2.zip

Created with Ionic CLI:

    ionic start hello2 --v2 --ts

Then build and run with

    ionic serve

which launches a local webserver at 8100 and opens the browser.

Opened VSCode and adapted launch.json to launch Chrome at localhost:8100. Browser opens, no ts breakpoint is hit.

**Comment by neilyoung** [comment]
Not only with ionic, also the simplest Angular 2 app has a problem with sourceRoot. The debugger complains, that sourceRoot is not specified and it is using "webRoot ... " instead, although tsConfig contains a sourceRoot entry. Does tsc have a problem to make a proper sourceRoot entry?

**Comment by roblourens** [comment]
Thanks for the project, I'll check it out soon. For a simple working Angular 2 project, check out the project under `examples/` in this repo.

**Comment by neilyoung** [comment]
Yes, confirmed. The difference is this:

My simple app:

```
tsconfig.json
    "sourceRoot": "application"   // Just to check whether it appears 

main.js.map
    {"version":3,"file":"main.js","sourceRoot":"application/","sources":["main.ts"],"names":[],....

diagnosticlog:
  ›SourceMap: no sourceRoot specified, using webRoot + script path dirname: /Users/me/Angular2/angular2-login/app
  
```

Your example:
```
tsconfig.json
   "sourceRoot": "blabla"       // Just to check whether it appears 
     
mock-heroes.js.map  
    {"version":3,"file":"mock-heroes.js","sourceRoot":"blabla/","sources":["mock-heroes.ts"],"names":[],...

diagnosticlog:  
    ›SourceMap: resolved sourceRoot blabla/ -> /Users/me/Angular2/vscode-chrome-debug/examples/angular2-tour-of-heroes/app/blabla

```  
  
Do you have a clue why - although in both cases there is a sourceRoot contained - the diagnostic log tells a different story?

**Comment by roblourens** [comment]
Your sample app has "sourceRoot: /source/" in the .js.map. I don't see where that would have come from. It's not in the tsconfig. How do I rebuild it to test? I haven't used ionic before.

**Comment by neilyoung** [comment]
ionic build 

As far as I know the "source" thing has been introduced by the last ionic beta and indicates, that the sources are inline.

**Comment by roblourens** [comment]
I don't have access to a mac at the moment, so I don't think I can build this, because it says it requires xcode. But I edited the launch config webRoot to `"webRoot": "${workspaceRoot}/www",` and the map file to be like `"sourceRoot":"/.."` to get out of www to the project root. Then the sources are like `"app/app.ts"` (I didn't change that) which can be resolved with the sourceRoot and webRoot to the ts file location. 

Note that "/.." isn't really a valid sourceRoot for a normal browser case since it's pointing outside the  web server root. You can also use a file:/// url to the actual path, this works for me - `"sourceRoot":"file:///c:/Users/roblo/Downloads/hello2/"`. I would recommend that. As long as you have inlined sources it will work in, say, Chrome devtools anyway, but if you want it to actually be resolvable outside of this extension, you need that or to move sources to be accessible from "localhost/".

I don't know what you have to do to build it with the correct sourceRoot, but if you can get it to be the right value then this should be workable.

**Comment by neilyoung** [comment]
Thanks for your efforts, already tried this. It doesn't work. I think it is because gulp is used to produce the sourcemap and tsconfig is ingored at all.

**Comment by roblourens** [comment]
Ok. I can't tell you how to configure your build but if you can get the sourcemap output to look right, then this should be totally doable! I'm closing this because I don't think I can be useful anymore.

**Comment by neilyoung** [comment]
Yes, thanks for your efforts

**Comment by flieks** [comment]
i'm confused, is sourcemaps used to debug in chrome or VS Code ? I assume the first.
It seems only NodeJS code can be debugged in VS Code. How to debug client side JS code in VS Code?

**Comment by Anujarya300** [comment]
I encountered same problem and for me this problem occurs when I am using webpack and added `sourceMapFilename: [name].map.js` variable in `output:` section of **webpack.dev.js** or **webpack.config.js** config file. Due to which debugger is not able to find actual map line number location on .typescript file which results on hit breakpoint on .js files insted .ts file.
Resolved by Removing  `sourceMapFilename: [name].map.js` variable in `output:` section of **webpack.dev.js** file.
Now hit F5, should work.

Thanks
