### ISSUE TITLE
Strange breakpoints behavior with webpack-dev-server

### ISSUE THREAD

**Issue by oorooroot** [Microsoft/vscode-chrome-debug#250]
I'm total new to webpack and trying to follow https://angular.io/docs/ts/latest/guide/webpack.html guide to configure webpack-based angular 2 environment, with chrome debugging(plugin version 1.1.0) enabled in vscode(1.6.0).

`webpack.dev.js:`
```
var webpackMerge = require('webpack-merge');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var commonConfig = require('./webpack.common.js');
var helpers = require('./helpers');

module.exports = webpackMerge(commonConfig, {
    //devtool: 'cheap-module-eval-source-map',
    devtool: 'source-map',

    output: {
        path: helpers.root('dist'),
        publicPath: 'http://localhost:3000/',
        filename: '[name].js',
        chunkFilename: '[id].chunk.js'
    },

    plugins: [
        new ExtractTextPlugin('[name].css')
    ],

    devServer: {
        historyApiFallback: true,
        stats: 'minimal'
    }
});
```
`launch.json`
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "sourceMaps": true,
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

![screenshot_5](https://cloud.githubusercontent.com/assets/21052689/19310661/e450c4fe-9093-11e6-84cd-66f0c05535d0.jpg)

Here is how my sample class looks. As you can see there two breakpoints setted up, and here is diagnostic output for them:

```
SourceMaps.setBP: Mapped http://localhost:3000/app.js:85:10 to d:\dev\sample\src\app\app.component.ts:11
SourceMaps.setBP: Mapped http://localhost:3000/app.js:86:10 to d:\dev\sample\src\app\app.component.ts:12
```

But when i try to set breakpoint at line 13:
```
SourceMaps.setBP: Can't map http://localhost:3000/app.js:98:6, keeping the line number as-is.
```
`http://localhost:3000/app.js` looks good for me, and here is app.js.map http://pastebin.com/VMyjkWxS
I have no idea, where to look about this trouble. Is it misconfigured or it some kind of bug?

**Comment by roblourens** [comment]
Can I see the app.js file? Make sure that it is built up to date and includes all the console.log statements.

**Comment by oorooroot** [comment]
Yep, it is up to date, Here it is http://pastebin.com/x9M2fD6i

**Comment by oorooroot** [comment]
Here is whole project https://github.com/oorooroot/sampleproject

**Comment by oorooroot** [comment]
Hmm, `app.js` and `app.js.map` that i posted are from the in memory strorage as they served by webpack-dev-server. Is it necessary to build them to project folder somehow, with `write-file-webpack-plugin` for example?

**Comment by roblourens** [comment]
Thanks, that's really useful. I see an issue if I set the breakpoint before launching the app - they get shifted when I refresh the page. But if I launch the app, then set breakpoints, I have no problem when I refresh the page. Do you see the same?

I think I see the bug for what I'm seeing.

**Comment by oorooroot** [comment]
In my environment, breakpoint shifted in both cases. When, set point, then run, and when set at runtime too.

**Comment by roblourens** [comment]
Ok, let's see where it's at when I fix this. In the meantime, a debugger statement should break in the right place at least.

Note to self, the pending breakpoint map is not cleared once the breakpoint is resolved. Should only be an issue when refreshing the page.

**Comment by roblourens** [comment]
Alright, try it out in 1.2.0, should be fixed

**Comment by oorooroot** [comment]
Still the same problem with new version.

![breakpoints_issue_2](https://cloud.githubusercontent.com/assets/21052689/19377642/a2266c24-91f0-11e6-806c-036e1b044055.gif)

**Comment by roblourens** [comment]
This is really weird. It works fine for me. Can you try setting a debugger statement or a few, and see if those are hit in the proper place, and if you can set breakpoints near them in the right place?

**Comment by TimBo93** [comment]
for debugger statements you can look at #247 maybe it is helpful.

**Comment by roblourens** [comment]
I think this will actually be the same as #247. Can you upgrade to 1.2.1 and let me know? Thanks!

**Comment by sinapis** [comment]
BP are hitting! However, if I uncheck both "All Exceptions" and "Uncaught Exceptions", breakpoints do not hit:

![bp not hit](https://cloud.githubusercontent.com/assets/15230040/19415543/dbe864da-937b-11e6-8e7e-15e118233a18.gif)

**Comment by roblourens** [comment]
Yeah so thats's global code that runs immediately, so you can't guarantee that your bp will bind in time to be hit. If you refresh the page, it should hit. When you hit the exception, maybe that gives the bp more time to bind.

**Comment by oorooroot** [comment]
It now works as expected, thank you!
