### ISSUE TITLE
pathMapping doesn't appear to work as expected (doesn't work when moving webRoot to pathMapping)

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode-chrome-debug#643]
This works fine for me:

```js
{
	"type": "chrome",
	"request": "launch",
	"name": "Launch web app",
	"url": "http://localhost:8080",
	"webRoot": "${workspaceFolder}/web",
	"preLaunchTask": "pub serve",
	"smartStep": true
}
```

However, if I remove webRoot and add the same thing to `pathMapping`, it never hits my breakpoint:

```js
{
	"type": "chrome",
	"request": "launch",
	"name": "Launch web app",
	"url": "http://localhost:8080",
	"preLaunchTask": "pub serve",
	"smartStep": true,
	"pathMapping": {
		"/": "${workspaceFolder}/web",
	}
}
```

The docs suggest that `webRoot` is just short-hand for `pathMapping` of `/` so I would expect them to behave the same. Let me know if I can get more info to debug.

**Comment by DanTup** [comment]
If I run `.scripts` in the debug console for the working one, I get:

```
› http://localhost:8080/dart/main.ddc.js
    - main.dart (/Users/danny/Dev/kids-games-dart/web/dart/main.dart)
```

For `pathMapping`:

```
› http://localhost:8080/dart/main.ddc.js (/Users/danny/Dev/kids-games-dart/web/dart/main.ddc.js)
```

So it seems like it's not mapping `main.ddc.js` on to `main.dart` anymore. Here's what that JS file looks like (I don't know why the map in the last line points at a different file and `main.dart` seems to be reference inside code, but whatever it's doing works when i use `webRoot`):

<img width="829" alt="screen shot 2018-04-06 at 21 43 12" src="https://user-images.githubusercontent.com/1078012/38443464-a7f0c14e-39e3-11e8-8c24-95fcbc5591be.png">

**Comment by roblourens** [comment]
pathMapping needs to check whether a file actually exists at the resolved location, like webRoot does.

**Comment by roblourens** [comment]
And also it must be used to resolve paths in sourcemap.ts

**Comment by roblourens** [comment]
This took more refactoring than I thought, but I've fixed up the places where pathMapping wasn't treated the same as webRoot. I need to do more testing before I publish this, but I'd really appreciate if you try it out @DanTup. I tried it with your project, and I can hit the breakpoint in main.dart fine, and can also add a mapping for nouns.dart like `"/packages/english_words/": "/Users/roblou/.pub-cache/hosted/pub.dartlang.org/english_words-3.1.0/lib"` and hit a breakpoint in that file if I open it in the same vscode window.

The sourcemaps in that file seem a little weird, and the positions are only resolved correctly if I set the breakpoint in one location - at line 4 column 28 right before the word `const` like 

![image](https://user-images.githubusercontent.com/323878/39488328-c281dd7a-4d36-11e8-8563-1f88da3da2a0.png)

but it works.

[debugger-for-chrome-4.3.1-beta.0.zip](https://github.com/Microsoft/vscode-chrome-debug/files/1964863/debugger-for-chrome-4.3.1-beta.0.zip)

**Comment by DanTup** [comment]
@roblourens I installed the beta version there but still see an issue.

I'm using this repo: https://github.com/DanTup/dart-web-app-test

If I put a breakpoint inside `main.dart` in the first line of `main()` and hit `F5`, it launches and hits the breakpoint fine. However, if I remove:

```js
"webRoot": "${workspaceFolder}/web",
```

and add:

```js
"pathMapping": {
	"/": "${workspaceFolder}/web",
3.1.0",
}
```

Then hit `F5` again, I don't hit the breakpoint (it does run the code and I see the console output). I didn't get as far as testing the more complex cases. Any ideas?

**Comment by roblourens** [comment]
Since I've published chrome-debug with a higher version number in the meantime, can you double check that it's not auto-updating past the beta to the latest marketplace version? You will have to set `"extensions.autoUpdate": false`. Sorry I should have called it v5.0.0.0-beta to avoid this.

![image](https://user-images.githubusercontent.com/323878/39960177-d4d0dd6a-55d2-11e8-8ea4-d18b9123f377.png)

**Comment by DanTup** [comment]
Aha, I didn't think it'd auto-update so quick. Indeed it'd gone up to 4.4.3. Disabling auto-updates and re-installing the vsix does fix that issue :-)

So, I think if you merge your fix this case is probably dealt with. I'll add some comments to https://github.com/dart-lang/build/issues/1025 for next steps as I think I'll need some assistance getting a project that includes everything required.

**Comment by roblourens** [comment]
Great, I'll merge this to master soon.
